### ISSUE TITLE
SSH support

### ISSUE THREAD

**Issue by SEAPUNK** [imdone/imdone-atom-github#7]
I noticed that your `githubPattern` checker checks for https Github URLs; will it be possible to add support for ssh Github repos? e.g. `ssh://git@github.com/example/repo`

**Comment by piascikj** [comment]
Should be fixed in 0.1.6

**Comment by SEAPUNK** [comment]
_removed because I didn't use the updated version_

**Comment by SEAPUNK** [comment]
If I'm reading your regex correctly (`/^(https|ssh):\/\/github\.com\/.*$/`), it still won't support SSH links properly: http://regexr.com/3catp

Try `^(https:\/\/|ssh:\/\/.*?@)github\.com\/.*$` (http://regexr.com/3cau2)

**Comment by piascikj** [comment]
Thanks for that.  I should have tested it myself :8ball:

**Comment by piascikj** [comment]
Fix is in 0.1.7

**Comment by SEAPUNK** [comment]
Seems to work, thanks.
